<a href="https://colab.research.google.com/github/Vashika17/Image-Processing-Model/blob/main/NumpyPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#datatypes
ar = np.array([1,2,3,4,5])

In [3]:
print(ar)

[1 2 3 4 5]


In [4]:
print(ar.dtype)

int64


In [9]:
ar = np.array([1,2,3,4,5], dtype=np.int8)

In [10]:
print(ar.dtype)

int8


In [12]:
print(f"{ar.nbytes} Bytes")

5 Bytes


In [13]:
arr=np.array([1,2,3,4,5], dtype=np.float16)
print(arr)
print(arr.dtype)
print(f"{arr.nbytes} Bytes")

[1. 2. 3. 4. 5.]
float16
10 Bytes


In [14]:
arr=np.array([1,2,3,4,5], dtype=np.complex64)
print(arr)
print(arr.dtype)
print(f"{arr.nbytes} Bytes")

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
complex64
40 Bytes


In [22]:
arr=np.array([1,2,"0",4,5], dtype=np.bool_)
print(arr)
print(arr.dtype)

[ True  True  True  True  True]
bool


In [28]:
arr=np.array([1,2,0,454,5], dtype=np.str_)
print(arr)
print(arr.dtype)

['1' '2' '0' '454' '5']
<U3


In [27]:
ar=np.array(["vashika","hi","hello"],dtype="<U5")
print(ar)
print(ar.dtype)

['vashi' 'hi' 'hello']
<U5


In [30]:
ar=np.array(["vashika","hi","hello",1,2,True], dtype=object)
print(ar)
print(ar.dtype)

['vashika' 'hi' 'hello' 1 2 True]
object


In [34]:
#Type conversion
arr=np.array([1,2,3,4,5])
cr=arr.astype(np.str_)

In [35]:
print(cr)
print(cr.dtype)

['1' '2' '3' '4' '5']
<U21


In [39]:
arr=np.array([1,2,"0",4,5])
cr=arr.astype(np.bool_)
print(cr)
print(cr.dtype)

[ True  True  True  True  True]
bool


In [40]:
#multidimensional arrays
ar=np.array([1,23,56,8,99,46,676])
print(ar.ndim)


1


In [50]:
ar=np.array([
              [1,23,56,8,99,46],
              [1,2,5,7,8,9]
    ])
print(ar.ndim)

2


In [48]:
abr=np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]]

])
print(abr.ndim)

3


In [53]:
acr=np.array([
    [[1,2,3,4],[5,6,7,91],[8,9,10,11],[12,13,14,15]],
    [[67,68,60,86],[24,53,65,55],[98,346,78,138],[345,87,208,456]]

])
print(acr.ndim)

3


In [55]:
#indexing in 3d array (layer--rows--columns)
print(acr)
print(acr[1,0,2])

[[[  1   2   3   4]
  [  5   6   7  91]
  [  8   9  10  11]
  [ 12  13  14  15]]

 [[ 67  68  60  86]
  [ 24  53  65  55]
  [ 98 346  78 138]
  [345  87 208 456]]]
60


In [57]:
#shaping
print(ar.shape)
print(ar)

(2, 6)
[[ 1 23 56  8 99 46]
 [ 1  2  5  7  8  9]]


In [58]:
#Reshaping
rear=ar.reshape(6,2)
print(rear)

[[ 1 23]
 [56  8]
 [99 46]
 [ 1  2]
 [ 5  7]
 [ 8  9]]


In [59]:
rear2=ar.reshape(1,12)
print(rear2)

[[ 1 23 56  8 99 46  1  2  5  7  8  9]]


In [60]:
rear3=ar.reshape(12,1)
print(rear3)

[[ 1]
 [23]
 [56]
 [ 8]
 [99]
 [46]
 [ 1]
 [ 2]
 [ 5]
 [ 7]
 [ 8]
 [ 9]]


In [61]:
rear4=ar.reshape(2,3,2) #layer--row--column
print(rear4)

[[[ 1 23]
  [56  8]
  [99 46]]

 [[ 1  2]
  [ 5  7]
  [ 8  9]]]


In [62]:
#no columns specified
rear5=ar.reshape(3,-1)
print(rear5)

[[ 1 23 56  8]
 [99 46  1  2]
 [ 5  7  8  9]]


In [63]:
#no rows specified
rear6=ar.reshape(-1,2)
print(rear6)

[[ 1 23]
 [56  8]
 [99 46]
 [ 1  2]
 [ 5  7]
 [ 8  9]]


In [64]:
#no layers specified
rear7=ar.reshape(-1,3,2)
print(rear7)

[[[ 1 23]
  [56  8]
  [99 46]]

 [[ 1  2]
  [ 5  7]
  [ 8  9]]]


In [68]:
#no layers, rows and columns specified
# because only one unknown dimension can be given
# no layer , no rows specified or any other combination is not allowed

rear8=ar.reshape(-1)
print(rear8)

[ 1 23 56  8 99 46  1  2  5  7  8  9]


In [71]:
#Array Slicing(Rows)
newarr=np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]

])
print(newarr[0])

[1 2 3 4 5]


In [72]:
print(newarr[-1])

[11 12 13 14 15]


In [74]:
print(newarr[0:2]) # 0 -> inclusive and 2 ->exclusive so goes upto 1 ie(0,1 printed)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [75]:
print(newarr[0:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [76]:
print(newarr[0:3:1]) #start--end--step count

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [78]:
print(newarr[0:3:2]) #start--end--step count

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [81]:
print(newarr[-1:-3:-1])

[[11 12 13 14 15]
 [ 6  7  8  9 10]]


In [86]:
print(newarr[::-1])

[[11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [87]:
print(newarr[0:3:3])

[[1 2 3 4 5]]


In [88]:
print(newarr[:3:3])#default 0 for start

[[1 2 3 4 5]]


In [89]:
print(newarr[::3])#default 0 for start,end

[[1 2 3 4 5]]


In [91]:
print(newarr[::]) # ::: not possible

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [92]:
print(newarr[:]) #start=0 end=end+1 step(i=i+1) default

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [93]:
print(newarr[1:])

[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [94]:
print(newarr[:1])

[[1 2 3 4 5]]


In [95]:
print(newarr[:-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [96]:
#Array Slicing(Columns)
# :, -> anything for rows
print(newarr[:,0]) #starts with 0 th column

[ 1  6 11]


In [97]:
print(newarr[:,1])

[ 2  7 12]


In [98]:
print(newarr[:,-1])

[ 5 10 15]


In [100]:
print(newarr[:,0:2]) # 0-> inclusive 2-> exclusive (0 th to 1 st column prints)

[[ 1  2]
 [ 6  7]
 [11 12]]


In [104]:
print(newarr[:,0:1]) #start + end

[[ 1]
 [ 6]
 [11]]


In [111]:
print(newarr)
print(newarr[:,0:3:2]) #start + end + step

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  3]
 [ 6  8]
 [11 13]]


In [110]:
print(newarr)
print(newarr[:,0:3:1]) #start + end + step

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [112]:
print(newarr)
print(newarr[:,::-1]) #start + end + step

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


In [113]:
#Array Slicing(Rows + Columns)
print(newarr)
print(newarr[1:3:1,1:3:1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 7  8]
 [12 13]]


In [114]:
print(newarr)
print(newarr[1:5:1,1:5:1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 7  8  9 10]
 [12 13 14 15]]


In [117]:
print(newarr)
print(newarr[0:3:1,0:3:1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [118]:
print(newarr)
print(newarr[0:3:2,0:3:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  3]
 [11 13]]


In [120]:
print(newarr)
print(newarr[0:5:1,0:5:1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [121]:
print(newarr)
print(newarr[0:5:2,0:5:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  3  5]
 [11 13 15]]


In [124]:
print(newarr)
print(newarr[1:3:1,0:2:1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 6  7]
 [11 12]]


In [125]:
print(newarr)
print(newarr[1:2:1,0:2:1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[6 7]]


In [150]:
print(newarr)
print(newarr[0:2:1,3:5:1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 4  5]
 [ 9 10]]


In [152]:
print(newarr)
print(newarr[1:4:1,3:5:1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 9 10]
 [14 15]]


In [154]:
print(newarr)
print(newarr[0:2:1,0:2:1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[1 2]
 [6 7]]


In [156]:
#Airthmetic Operators (Only Same Sized Arrays)
ar=np.array([1,2,3,4,5])
br=np.array([6,7,8,9,10])
print(ar+br)

[ 7  9 11 13 15]


In [175]:

print(ar*br)

[ 6 14 24 36 50]


In [174]:
print(ar)
print(br)
print(ar/br)

[1 2 3 4 5]
[ 6  7  8  9 10]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [176]:
print(ar)
print(br)
print(ar**br) #1^6, 2^7...

[1 2 3 4 5]
[ 6  7  8  9 10]
[      1     128    6561  262144 9765625]


In [157]:
ar=np.array([1,2,3,4,5])
print(ar+1)

[2 3 4 5 6]


In [161]:
ar=np.array([1,2,3,4,5])
print(ar/5)

[0.2 0.4 0.6 0.8 1. ]


In [158]:
ar=np.array([1,2,3,4,5])
print(ar-1)

[0 1 2 3 4]


In [159]:
ar=np.array([1,2,3,4,5])
print(ar*1)

[1 2 3 4 5]


In [160]:
ar=np.array([1,2,3,4,5])
print(ar)
print(br)
print(ar*br)

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 6 14 24 36 50]


In [162]:
ar=np.array([1,2,3,4,5])
print(ar**2) #power of 2 (1^2 , 2^2, 3^2....)

[ 1  4  9 16 25]


In [163]:
print(np.sqrt(ar))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [164]:
cr=np.array([1.23,2.345,3.455,4.566]) #see 4.566 is round offed to 5
print(np.round(cr))

[1. 2. 3. 5.]


In [169]:
print(cr)
print(np.floor(cr)) #see 4.566 is floor round offed to 4

[1.23  2.345 3.455 4.566]
[1. 2. 3. 4.]


In [168]:
print(cr)
print(np.ceil(cr)) #see 1.23 is upper round offed to 2

[1.23  2.345 3.455 4.566]
[2. 3. 4. 5.]


In [177]:
brr=np.array([1,2,3,4,5,6,7,8,9,10]) # there is also many like <,<=,>,>=,==
print(brr>6)

[False False False False False False  True  True  True  True]


In [178]:
brr=np.array([1,2,3,4,5,6,7,8,9,10])
print(brr>=6)

[False False False False False  True  True  True  True  True]


In [179]:
brr=np.array([1,2,3,4,5,6,7,8,9,10])
print(brr==6)

[False False False False False  True False False False False]


In [187]:
#find and replace the value
brr=np.array([1,2,3,4,5,6,7,8,9,10])
brr[brr>8]=11
print(brr)

[ 1  2  3  4  5  6  7  8 11 11]


In [188]:
#Broadcasting (For Different Sized Arrays)
ar=np.array([
      [1,2,3],  # 1 2 3
      [4,5,6],
      [7,8,9]    #(3,3) (1,3) atleast one '1' in column/row , same no.of row /column in both array
    ])           #(3,3) (3,2)-> not applicable
br=np.array([1,2,3])
print(ar*br)


[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [192]:
ar=np.array([
      [1,2,3], #1
      [4,5,6], #2
      [7,8,9]  #3
    ])
br=np.array([[1],[2],[3]])  #(3,3) (3,1)
print(br)
print(ar*br)

[[1]
 [2]
 [3]]
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]
